config/routes.rb
Rails.application.routes.draw do

 

  get 'users/show'
  devise_for :users,
    controllers: {
    sessions: 'users/sessions',
    registrations: "users/registrations",
    omniauth_callbacks: 'users/omniauth_callbacks'
   }

  root 'top#index'
  get 'top/index' => 'top#index', as: 'top_index'
  get 'top/top' => 'top#top', as: 'top_top'
  get 'targets/calendar' => 'targets#calendar', as: 'target_calendar'

  resources :users
  resources :targets do
    resources :patiences, only: [:new, :create, :show, :edit, :update, :destroy]
    resource :favorites, only: [:create, :destroy]
    resources :post_comments, only: [:create, :destroy]

  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
	belongs_to :user
    belongs_to :target
end

app/models/patience.rb
class Patience < ApplicationRecord
	belongs_to :target
	validates :price, presence: true
	validates :name, presence: true
end

app/models/post_comment.rb
class PostComment < ApplicationRecord
	belongs_to :user
    belongs_to :target
end

app/models/sns_credential.rb
class SnsCredential < ApplicationRecord
  belongs_to :user
end

app/models/target.rb
class Target < ApplicationRecord

	belongs_to :user
	has_many :patiences, dependent: :destroy
	has_many :post_comments, dependent: :destroy
	has_many :favorites, dependent: :destroy
	validates :title, presence: true
	validates :price, presence: true

	enum target_status:{'Topicに設定':0,'Topicに表示しない':1}
    attribute :target_status, :integer, default: 0


  def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
  end
end

app/models/user.rb
class User < ApplicationRecord
  attachment :profile_image

  has_many :targets, dependent: :destroy
  has_many :post_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :sns_credentials, dependent: :destroy

  enum rank_status:{'見習い':0,'一般':1}
    attribute :rank_status, :integer, default: 0

  devise :database_authenticatable, :registerable,
        :recoverable, :rememberable, :validatable,
        :omniauthable, omniauth_providers: %i[facebook google_oauth2]

  def self.without_sns_data(auth)
    user = User.where(email: auth.info.email).first

      if user.present?
        sns = SnsCredential.create(
          uid: auth.uid,
          provider: auth.provider,
          user_id: user.id
        )
      else
        user = User.new(
          name: auth.info.name,
          email: auth.info.email,
        )
        sns = SnsCredential.new(
          uid: auth.uid,
          provider: auth.provider
        )
      end
      return { user: user ,sns: sns}
    end

  def self.with_sns_data(auth, snscredential)
    user = User.where(id: snscredential.user_id).first
    unless user.present?
      user = User.new(
        name: auth.info.name,
        email: auth.info.email,
      )
    end
    return {user: user}
  end

  def self.find_oauth(auth)
    uid = auth.uid
    provider = auth.provider
    snscredential = SnsCredential.where(uid: uid, provider: provider).first
    if snscredential.present?
      user = with_sns_data(auth, snscredential)[:user]
      sns = snscredential
    else
      user = without_sns_data(auth)[:user]
      sns = without_sns_data(auth)[:sns]
    end
    return { user: user ,sns: sns}
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
    devise_parameter_sanitizer.permit(:account_update, keys: [:name])
  end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  def create
    @target = Target.find(params[:target_id])
    favorite = current_user.favorites.new(target_id: @target.id)
    favorite.save
  end
  def destroy
    @target = Target.find(params[:target_id])
    favorite = current_user.favorites.find_by(target_id: @target.id)
    favorite.destroy
  end
end

app/controllers/patiences_controller.rb
class PatiencesController < ApplicationController

  def new
    @patience = Patience.new
    @target = Target.find_by(id: params[:target_id])
  end

  def create
    @patience = Patience.new(patience_params)
    @target = Target.find_by(id: params[:target_id])
    if @patience.save
      redirect_to targets_path
    else
      render action: :new
    end
  end

  def show
    @patience = Patience.find(params[:id])
  end

  def update
    @patience = Patience.find(params[:id])
    if @patience.update(patience_params)
      redirect_to :root
    else
      render action: :edit
    end
  end

  def edit
    @patience = Patience.find(params[:id])
  end

  def destroy
    @patience = Patience.find(params[:id])
    @patience.destroy
    redirect_to targets_path
  end

  private
  def patience_params
    params.require(:patience).permit(:name, :price, :target_id)
  end
end

app/controllers/post_comments_controller.rb
class PostCommentsController < ApplicationController

  def create
    @post_comment = PostComment.new
    @target = Target.find(params[:target_id])
    @comment = current_user.post_comments.new(post_comment_params)
    @comment.target_id = @target.id
    @comment.save
    redirect_back(fallback_location: root_path)

  end
  def destroy
    PostComment.find_by(id: params[:id], target_id: params[:target_id]).destroy
    redirect_to target_path(params[:target_id])
  end
  private
  def post_comment_params
    params.require(:post_comment).permit(:comment)
  end
end

app/controllers/targets_controller.rb
class TargetsController < ApplicationController
  before_action :authenticate_user!
  def index
    # ここのwhereでuser_idが現在ログイン中のユーザーのレコードを持ってこれる
    @targets = Target.where(user: current_user).order("created_at ASC")
  end

  def new
    @target = Target.new
  end

  def edit
    @target = Target.find(params[:id])
  end

  def update
      @target = Target.find(params[:id])
    if @target.update(target_params)
      redirect_to targets_path
    else
      render :edit
    end
  end

  def destroy
    @target = Target.find(params[:id])
    @target.destroy
    redirect_to targets_path
  end

  def create
      @target = Target.new(target_params)
    if @target.save
      redirect_to targets_path
    else
      render :new
    end
  end

  def show
    @target = Target.find(params[:id])
    @post_comment = PostComment.new
  end

  def calendar
    @targets = Target.where(user: current_user).order("created_at ASC")
  end

  private
  def target_params
    params.require(:target).permit(:title, :price, :start_time, :target_status).merge(user: current_user)
  end
end

app/controllers/top_controller.rb
class TopController < ApplicationController

  def top
  end
  def index
    @users = User.all
    @targets = Target.where(user: current_user).order("created_at ASC")
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    @users = User.all
    @targets = Target.all
    @targets = Target.page(params[:page]).per(5)
  end
  def show
    @user = User.find(params[:id])
    @targets = Target.all
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      flash[:notice] = "successfully"
      redirect_to user_path(@user)
    else
      render :edit
    end
  end


  private
  def user_params
    params.require(:user).permit(:name, :body, :profile_image, :rank_status)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/omniauth_callbacks_helper.rb
module OmniauthCallbacksHelper
end

app/helpers/patiences_helper.rb
module PatiencesHelper
end

app/helpers/post_comments_helper.rb
module PostCommentsHelper
end

app/helpers/targets_helper.rb
module TargetsHelper
end

app/helpers/top_helper.rb
module TopHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/top/index.html.erb
<div class="container">
  <div class="all-title">
    <h1>Top Page</h2>
  </div>
</div>

<div class="topPage">
  <div class="container">
    <div class="row">
      <div class="rank-box">
        <div class="col-6">
          <% array = [] %>
            <% @targets.each do |target| %>
              <% target.patiences.each do |patience| %>
                <% array << patience.price.to_i %>
              <% end %>
            <% end %>
            <div class="text-rank">
              <h1>Total GAMAN</h1>
              <h1>￥<%= array.sum.to_i.to_s(:delimited) %></h1>
              <h1>RANK</h1>
            <% if 100000 <= array.sum %>
              <h1>[フカヒレ]</h1>
              <%= image_tag asset_path("hukahire.png",alt: ""),width: "300px" %>
            <% elsif 50000 <= array.sum %>
              <h1>[キャビア]</h1>
              <%= image_tag asset_path("kyabia.png",alt: ""),width: "300px" %>
            <% elsif 40000 <= array.sum %>
              <h1>[メガロドン]</h1>
              <%= image_tag asset_path("megarodon.png",alt: ""),width: "300px" %>
            <% elsif 30000 <= array.sum %>
              <h1>[チョウザメ]</h1>
              <%= image_tag asset_path("tyouzame.png",alt: ""),width: "300px" %>
            <% else 10000 <= array.sum %>
              <h1>[普通のサメ]</h1>
              <%= image_tag asset_path("same.png",alt: ""),width: "300px" %>
            <% end %>
          </div>
        </div>
      </div>
      <div class="col-6">
        <h1>Topic!!!!</h1>
        <div class="topPage">
          <div class="targetWrapper">
            <% @targets.each do |target| %>
              <% if target.target_status == "Topicに設定" %>
                <div class="target">
                  <div class="target_header">
                    <h2 class="target_header_title">目標:<%= link_to target.title ,target_path(target) %></h2>
                    <h2 class="target_header_title"><%= target.price.to_i %>円</h2>
                    <div class="target_header_action">
                      <%= link_to(content_tag(:i, '', class: 'fas fa-pen'), edit_target_path(target)) %>
                      <%= link_to "",target, method: :delete,class: 'fas fa-trash-alt' %>
                    </div>
                  </div>
                  <% array = [] %>
                  <div class="patienceWrapper">
                    <% target.patiences.each do |patience| %>
                      <% array << patience.price.to_i %>
                        <div class="patience">
                          <h3 class="patience_title">
                            <%= link_to patience.name, target_patience_path(target,patience) %>&nbsp;&nbsp;&nbsp;&nbsp;<%= patience.price %>円
                          </h3>
                        </div>
                    <% end %>
                      <h6>我慢金額合計<%= array.sum %>円</h6>
                      <h6>達成まで<%= target.price.to_i - array.sum %>円</h6>
                    <% if target.price.to_i <= array.sum %>
                      <div class="atsu-mori" >我慢上手</div>
                    <% end %>
                    <%= link_to "さらに我慢を追加", new_target_patience_path(target),class: 'fas fa-bars' %>
                  </div>
                </div>
              <% end %>
            <% end %>
          </div>
          <%= link_to "新しく目標を作る", new_target_path, class: "btn button-index" %>
        </div>
      </div>
    </div>
  </div>
</div>