config/routes.rb
Rails.application.routes.draw do

 

  get 'users/show'
  devise_for :users,
    controllers: {
    sessions: 'users/sessions',
    registrations: "users/registrations",
    omniauth_callbacks: 'users/omniauth_callbacks'
   }

  root 'top#index'
  get 'top/index' => 'top#index', as: 'top_index'
  get 'top/top' => 'top#top', as: 'top_top'
  get 'targets/calendar' => 'targets#calendar', as: 'target_calendar'

  resources :users
  resources :targets do
    resources :patiences, only: [:new, :create, :show, :edit, :update, :destroy]
    resource :favorites, only: [:create, :destroy]
    resources :post_comments, only: [:create, :destroy]

  end
end

app/models/user.rb
class User < ApplicationRecord
  attachment :profile_image

  has_many :targets, dependent: :destroy
  has_many :post_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :sns_credentials, dependent: :destroy

  enum rank_status:{'見習い':0,'一般':1}
    attribute :rank_status, :integer, default: 0

  devise :database_authenticatable, :registerable,
        :recoverable, :rememberable, :validatable,
        :omniauthable, omniauth_providers: %i[facebook google_oauth2]

  def self.without_sns_data(auth)
    user = User.where(email: auth.info.email).first

      if user.present?
        sns = SnsCredential.create(
          uid: auth.uid,
          provider: auth.provider,
          user_id: user.id
        )
      else
        user = User.new(
          name: auth.info.name,
          email: auth.info.email,
        )
        sns = SnsCredential.new(
          uid: auth.uid,
          provider: auth.provider
        )
      end
      return { user: user ,sns: sns}
    end

  def self.with_sns_data(auth, snscredential)
    user = User.where(id: snscredential.user_id).first
    unless user.present?
      user = User.new(
        name: auth.info.name,
        email: auth.info.email,
      )
    end
    return {user: user}
  end

  def self.find_oauth(auth)
    uid = auth.uid
    provider = auth.provider
    snscredential = SnsCredential.where(uid: uid, provider: provider).first
    if snscredential.present?
      user = with_sns_data(auth, snscredential)[:user]
      sns = snscredential
    else
      user = without_sns_data(auth)[:user]
      sns = without_sns_data(auth)[:sns]
    end
    return { user: user ,sns: sns}
  end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
def facebook
    callback_for(:facebook)
  end

  def google_oauth2
    callback_for(:google)
  end


  def callback_for(provider)
    @omniauth = request.env['omniauth.auth']
    info = User.find_oauth(@omniauth)
    @user = info[:user]
    if @user.persisted?
      sign_in_and_redirect @user, event: :authentication
      set_flash_message(:notice, :success, kind: "#{provider}".capitalize) if is_navigational_format?
    else
      @sns = info[:sns]
      render template: "devise/registrations/new"
    end
  end

  def failure
    redirect_to root_path and return
  end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  
  def create
   super
     #NotificationMailer.send_confirm_to_user(@user).deliver
  end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    @users = User.all
    @targets = Target.all
    @targets = Target.page(params[:page]).per(5)
  end
  def show
    @user = User.find(params[:id])
    @targets = Target.all
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      flash[:notice] = "successfully"
      redirect_to user_path(@user)
    else
      render :edit
    end
  end


  private
  def user_params
    params.require(:user).permit(:name, :body, :profile_image, :rank_status)
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_favorite.html.erb
<% if target.favorited_by?(current_user) %>
  <%= link_to target_favorites_path(target), method: :delete, remote: true do %>
    <i class="fas fa-fish" aria-hidden="true" style="color: red;"></i>
    <%= target.favorites.count %>
  <% end %>
<% else %>
  <%= link_to target_favorites_path(target), method: :post, remote: true do %>
    <i class="fas fa-fish" aria-hidden="true"></i>
    <%= target.favorites.count %>
  <% end %>
<% end %>

app/views/users/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-4"></div>
    <div class="col-4">
      <% if @user.errors.any? %>
        <%= @user.errors.count %>error
        <% @user.errors.full_messages.each do |message| %>
            <%= message %>
        <% end %>
      <% end %>
      <%= form_with model: @user, url: { action: :update }, local: true do |f| %>
        <div class="form-group">
          <%= f.label :name %>
          <%= f.text_field :name, autofocus: true,  placeholder: "名前",class: "input form-control" %>
        </div>
        <div class="form-group">
          <%= f.label :body %>
          <%= f.text_area :body, autofocus: true,  placeholder: "自己紹介",class: "input form-control" %>
        </div>
        <div class="form-group">
          <%= f.attachment_field :profile_image %>
        </div>
        <div class="form-group">
          <%= f.submit "編集",class: "btn btn-outline-dark",style: "width:300px" %>
        </div>
        <div class="col-4"></div>
      <% end %>
    </div>
  </div>
</div>

app/views/users/index.html.erb
<div class="container">
  <div class="all-title">
    <h1>みんなのGAMAN</h2>
  </div>
</div>

<div class="container">
  <div class="row">
    <table class="table">
      <thead>
        <tr>
          <th>image</th>
          <th>User</th>
          <th>Target</th>
          <th>price</th>
          <th>NiceGaman</th>
        </tr>
      </thead>
        <% @targets.each do |target| %>
          <tbody>
            <tr>
              <td><%= attachment_image_tag target.user, :profile_image,fallback:"noimage.jpg", format: 'jpeg' , size: "50x50",class:"rounded-circle icon_image mr-3 mb-3" %></td>
              <td><%= link_to user_path(target.user.id) do %>
                    <%= target.user.name %>
                  <% end %></td>
              <td><%= link_to target.title,target_path(target) %></td>
              <td><%= target.price.to_i.to_s(:delimited) %></td>
              <td class="target_<%= target.id %>">
                <%= render "users/favorite",target: target %>
              </td>
            </tr>
          </tbody>
        <% end %>
      <%= paginate @targets %>
    </table>
  </div>
</div>

app/views/users/show.html.erb
<div class="container">
  <div class="all-title">
    <h1><%= @user.name %>'s Profile</h2>
  </div>
</div>

<div class="window">
  <div class="box header-show">
    <div class="img-show"><%= attachment_image_tag @user, :profile_image, fallback:"noimage.jpg", format: 'jpeg' , size: "200x150" %></div>
      <h2><%= @user.name %></h2>
    <div><%= @user.body %></div>
    <% if @user == current_user %>
      <%= link_to "Profile Edit",edit_user_path(@user),class: "btn show-edit" %>
    <% end %>
  </div>
  <div class="box footer">
    <% array = [] %>
    <% @user.targets.each do |target| %>
      <% target.patiences.each do |patience| %>
        <% array << patience.price.to_i %>
      <% end %>
    <% end %>
      <h3>Total GAMAN</h3>
    <div class="text-center">
      <h4>￥<%= array.sum %></h4>

      <% if 100000 <= array.sum %>
        <h4>[フカヒレ]</h4>
        <%= image_tag asset_path("hukahire.png",alt: ""),width: "150px" %>
      <% elsif 50000 <= array.sum %>
        <h4>[キャビア]</h4>
        <%= image_tag asset_path("kyabia.png",alt: ""),width: "150px" %>
      <% elsif 40000 <= array.sum %>
        <h4>[メガロドン]</h4>
        <%= image_tag asset_path("megarodon.png",alt: ""),width: "150px" %>
      <% elsif 30000 <= array.sum %>
        <h4>[チョウザメ]</h4>
        <%= image_tag asset_path("tyouzame.png",alt: ""),width: "150px" %>
      <% else 10000 <= array.sum %>
        <h4>[普通のサメ]</h4>
        <%= image_tag asset_path("same.png",alt: ""),width: "150px" %>
      <% end %>
    </div>
  </div>
</div>